### ISSUE TITLE
Ajout d'une licence

### ISSUE THREAD

**Issue by bzg** [fab-geocommuns/BatID#10]
Le projet ne semble pas contenir de dépendances, vous pouvez le publier sous licence Expat (aussi appelée "licence MIT"), Apache 2.0 ou l'une des BSD [autorisées](https://www.data.gouv.fr/fr/pages/legal/licences/).

**Comment by fe51** [comment]
Hello Bastien, merci pour le rappel.

On va publier sous Apache 2.0, je viens de faire les modifications nécessaires.

**Comment by bzg** [comment]
Parfait, merci !
